version: '3.8'

services:
  medical-ai-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add your OpenAI API key here or use .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    # Optional: Add volume for persistent data if needed
    # volumes:
    #   - ./data:/app/data 